spring.application.name=obd_server

spring.datasource.url=jdbc:mysql://localhost:3306/obd?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=111111
spring.jpa.hibernate.ddl-auto=update
